[general]
id = "br1-ff00_0_132-1"
config_dir = "gen/ISD1/ASff00_0_132/br1-ff00_0_132-1"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:31]:30442"

[log.file]
path = "logs/br1-ff00_0_132-1.log"
level = "debug"
