[general]
id = "sd2-ff00_0_221"
config_dir = "gen/ISD2/ASff00_0_221/endhost"
reconnect_to_dispatcher = true

[trust_db]
backend = "sqlite"
connection = "gen-cache/sd2-ff00_0_221.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_221.path.db"

[sd]
address = "127.0.0.133:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.133:30455"

[log.file]
path = "logs/sd2-ff00_0_221.log"
level = "debug"
