description = "ISD 2"
version = 1
base_version = 1
voting_quorum = 2
grace_period = "0s"
trust_reset_allowed = true
votes = []

[validity]
  not_before = 1589893254
  validity = "1y"

[primary_ases]
  [primary_ases."ff00:0:210"]
    attributes = ["authoritative", "core", "issuing", "voting"]
    issuing_grant_key_version = 1
    voting_online_key_version = 1
    voting_offline_key_version = 1
  [primary_ases."ff00:0:220"]
    attributes = ["authoritative", "core", "issuing", "voting"]
    issuing_grant_key_version = 1
    voting_online_key_version = 1
    voting_offline_key_version = 1

