[general]
id = "br2-ff00_0_220-4"
config_dir = "gen/ISD2/ASff00_0_220/br2-ff00_0_220-4"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:44]:30442"

[log.file]
path = "logs/br2-ff00_0_220-4.log"
level = "debug"
