[general]
id = "sd2-ff00_0_212"
config_dir = "gen/ISD2/ASff00_0_212/endhost"
reconnect_to_dispatcher = true

[trust_db]
backend = "sqlite"
connection = "gen-cache/sd2-ff00_0_212.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_212.path.db"

[sd]
address = "127.0.0.108:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.108:30455"

[log.file]
path = "logs/sd2-ff00_0_212.log"
level = "debug"
