[general]
id = "br2-ff00_0_220-2"
config_dir = "gen/ISD2/ASff00_0_220/br2-ff00_0_220-2"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:42]:30442"

[log.file]
path = "logs/br2-ff00_0_220-2.log"
level = "debug"
