[general]
id = "sd1-ff00_0_133"
config_dir = "gen/ISD1/ASff00_0_133/endhost"
reconnect_to_dispatcher = true

[trust_db]
backend = "sqlite"
connection = "gen-cache/sd1-ff00_0_133.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_133.path.db"

[sd]
address = "127.0.0.100:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.100:30455"

[log.file]
path = "logs/sd1-ff00_0_133.log"
level = "debug"
