[general]
id = "sd1-ff00_0_111"
config_dir = "gen/ISD1/ASff00_0_111/endhost"
reconnect_to_dispatcher = true

[trust_db]
backend = "sqlite"
connection = "gen-cache/sd1-ff00_0_111.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_111.path.db"

[sd]
address = "[fd00:f00d:cafe::7f00:1d]:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:1d]:30455"

[log.file]
path = "logs/sd1-ff00_0_111.log"
level = "debug"
