[general]
id = "cs1-ff00_0_133-1"
config_dir = "gen/ISD1/ASff00_0_133/cs1-ff00_0_133-1"
reconnect_to_dispatcher = true

[trust_db]
backend = "sqlite"
connection = "gen-cache/cs1-ff00_0_133-1.trust.db"

[beacon_db]
backend = "sqlite"
connection = "gen-cache/cs1-ff00_0_133-1.beacon.db"

[path_db]
backend = "sqlite"
connection = "gen-cache/cs1-ff00_0_133-1.path.db"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "[127.0.0.99]:30452"

[quic]
address = "[127.0.0.99]:30352"
cert_file = "gen-certs/tls.pem"
key_file = "gen-certs/tls.key"
resolution_fraction = 0.4

[log.file]
path = "logs/cs1-ff00_0_133-1.log"
level = "debug"
