[general]
id = "cs2-ff00_0_222-1"
config_dir = "gen/ISD2/ASff00_0_222/cs2-ff00_0_222-1"
reconnect_to_dispatcher = true

[trust_db]
backend = "sqlite"
connection = "gen-cache/cs2-ff00_0_222-1.trust.db"

[beacon_db]
backend = "sqlite"
connection = "gen-cache/cs2-ff00_0_222-1.beacon.db"

[path_db]
backend = "sqlite"
connection = "gen-cache/cs2-ff00_0_222-1.path.db"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:53]:30452"

[quic]
address = "[fd00:f00d:cafe::7f00:53]:30352"
cert_file = "gen-certs/tls.pem"
key_file = "gen-certs/tls.key"
resolution_fraction = 0.4

[log.file]
path = "logs/cs2-ff00_0_222-1.log"
level = "debug"
