[general]
id = "br1-ff00_0_110-2"
config_dir = "gen/ISD1/ASff00_0_110/br1-ff00_0_110-2"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:12]:30442"

[log.file]
path = "logs/br1-ff00_0_110-2.log"
level = "debug"
