[general]
id = "br1-ff00_0_111-1"
config_dir = "gen/ISD1/ASff00_0_111/br1-ff00_0_111-1"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:19]:30442"

[log.file]
path = "logs/br1-ff00_0_111-1.log"
level = "debug"
